package com.example.myapplication

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF000000)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF000000)
val md_theme_light_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_light_secondary = Color(0xFF000000)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF000000)
val md_theme_light_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_light_tertiary = Color(0xFF000000)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF000000)
val md_theme_light_onTertiaryContainer = Color(0xFFFFFFFF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFF000000)
val md_theme_light_onBackground = Color(0xFFFFFFFF)
val md_theme_light_surface = Color(0xFF000000)
val md_theme_light_onSurface = Color(0xFFFFFFFF)
val md_theme_light_surfaceVariant = Color(0xFF000000)
val md_theme_light_onSurfaceVariant = Color(0xFFFFFFFF)
val md_theme_light_outline = Color(0xFF767676)
val md_theme_light_inverseOnSurface = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFFFFFFFF)
val md_theme_light_inversePrimary = Color(0xFFFFFFFF)
val md_theme_light_surfaceTint = Color(0xFF000000)
val md_theme_light_outlineVariant = Color(0xFFC6C6C6)
val md_theme_light_scrim = Color(0xFF000000)
